name: ten_ten_one
description: A non-custodial Bitcoin and Lightning wallet for the masses.  Trade derivatives, bet on your favorite team or set up a non-custodial savings account on Bitcoin. Powered by Lightning and DLCs. Built with ❤️.
publish_to: none
version: 0.3.1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.51.0
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.1.0
  ffi: ^2.0.1
  provider: ^6.0.0
  intl: ^0.17.0
  go_router: ^5.1.5
  flutter_svg: ^1.1.6
  f_logs: ^2.0.1
  flutter_speed_dial: ^6.2.0
  decimal: ^2.3.0
  font_awesome_flutter: ^10.2.1
  uuid: ^3.0.7
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  webview_flutter_plus: ^0.3.0
  flutter_native_splash: ^2.2.16
  feedback: ^2.5.0
  flutter_email_sender: ^5.2.0
  device_info_plus: ^8.0.0
  mobile_scanner: ^2.1.0
  shared_preferences: ^2.0.15
  onboarding: ^3.1.0
  package_info_plus: ^3.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.2.1
  build_runner: ^2.2.0
  ffigen: ^7.2.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/10101_logo.png
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  macos:
    generate: true
    image_path: assets/10101_logo.png
  windows:
    generate: true
    image_path: assets/10101_logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/10101_logo.svg
    - assets/10101_logo.png
    - satoshi_regular_black.svg
    - assets/Onboarding1-OneAppAllthingsBitcoin.png
    - assets/Onboarding2-YourKeysYourBitcoin.png
    - assets/Onboarding3-TradeNonCustodial.png
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/10101.finance_logo_1500x1500.png
  android_12: null
