// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';
import 'package:meta/meta.dart';

class TenTenOnePlatform extends FlutterRustBridgeBase<TenTenOneWire>
    with FlutterRustBridgeSetupMixin {
  TenTenOnePlatform(FutureOr<WasmModule> dylib) : super(TenTenOneWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;
// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  Object api2wire_i64(int raw) {
    return castNativeBigInt(raw);
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
}

// Section: WASM wire module

@JS('wasm_bindgen')
external TenTenOneWasmModule get wasmModule;

@JS()
@anonymous
class TenTenOneWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external TenTenOneWasmModule bind(dynamic thisArg, String moduleName);
  external void wire_build_wallet(NativePortType port_, Object port, String data_dir);
}

// Section: WASM wire connector

class TenTenOneWire extends FlutterRustBridgeWasmWireBase<TenTenOneWasmModule> {
  TenTenOneWire(FutureOr<WasmModule> module) : super(WasmModule.cast<TenTenOneWasmModule>(module));

  void wire_build_wallet(NativePortType port_, Object port, String data_dir) =>
      wasmModule.wire_build_wallet(port_, port, data_dir);
}
