// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';
import 'package:meta/meta.dart';

class TenTenOneImpl implements TenTenOne {
  final TenTenOnePlatform _platform;
  factory TenTenOneImpl(ExternalLibrary dylib) => TenTenOneImpl.raw(TenTenOnePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory TenTenOneImpl.wasm(FutureOr<WasmModule> module) =>
      TenTenOneImpl(module as ExternalLibrary);
  TenTenOneImpl.raw(this._platform);
  Future<int> buildWallet({required int port, required String dataDir, dynamic hint}) =>
      _platform.executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_build_wallet(
            port_, _platform.api2wire_i64(port), _platform.api2wire_String(dataDir)),
        parseSuccessData: _wire2api_i32,
        constMeta: kBuildWalletConstMeta,
        argValues: [port, dataDir],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kBuildWalletConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "build_wallet",
        argNames: ["port", "dataDir"],
      );

// Section: wire2api

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}
