[package]
name = "ten_ten_one"
version = "0.1.0"
edition = "2021"

[lib]
name = "ten_ten_one"
crate-type = ["cdylib", "staticlib"] # Android needs cdylib, whereas iOS staticlib

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bdk = "0.24.0"
bip39 = "1.0.1"
flutter_rust_bridge = "1.49.1"
hkdf = "0.12"
rand = "^0.6.0"
sha2 = "0.10"
state = "0.5.3"
