[package]
name = "ten_ten_one"
version = "0.1.0"
edition = "2018"

[lib]
name = "ten_ten_one"
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
flutter_rust_bridge = "1.49.0"
num = "0.4"                                             # unrelated to Flutter Rust Bridge. Used only to draw beautiful photos.
image = "0.24.3"                                        # unrelated to Flutter Rust Bridge. Used only to draw beautiful photos.
crossbeam = "0.8"                                       # unrelated to Flutter Rust Bridge. Used only to draw beautiful photos.
