[package]
name = "ten_ten_one"
version = "0.1.0"
edition = "2018"

[lib]
name = "ten_ten_one"
crate-type = ["cdylib", "staticlib"] # Android needs cdylib, whereas iOS staticlib

[build-dependencies]
flutter_rust_bridge_codegen = { version = "1.49.0", features = [ "chrono" ] }

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
flutter_rust_bridge = "1.49.0"