[package]
name = "tentenone"
version = "0.1.0"
edition = "2021"

[lib]
name = "tentenone"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
flutter_rust_bridge = "1"