name: "Create release"

on:
  pull_request:
    types:
      - closed

env:
  FLUTTER_VERSION: "3.3.1"

jobs:
  build:
    runs-on: macos-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    outputs:
      ANDROID_APK_NAME: ${{ steps.build.outputs.ANDROID_APK_NAME }}
    steps:
      - uses: actions/checkout@v2

      # #499, https://github.com/actions/virtual-environments/issues/5595
      - name: Configure ndk
        run: |
          ANDROID_HOME=$HOME/Library/Android/sdk
          SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager

          echo y | $SDKMANAGER "ndk;21.4.7075529"

          ln -sfn $ANDROID_HOME/ndk/21.4.7075529 $ANDROID_HOME/ndk-bundle

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8.x" # "betterprogramming.pub" says must be java "8"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          architecture: x64

      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./rust/target
          key: ${{ runner.os }}-cargo-integrate-android-${{ hashFiles('**/Cargo.lock') }}-${{ steps.checkout.outputs.rustc_hash }}

      - name: Install FFI bindings
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: cargo install flutter_rust_bridge_codegen

      - name: Generate FFI bindings
        run: make gen

      - name: Add Rust targets
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Install `cargo-ndk`
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: cargo install cargo-ndk --force

      - name: Build Rust lib
        working-directory: ./rust
        run: cargo ndk -o ../android/app/src/main/jniLibs build

      - name: Parse version from pubspec.yaml
        id: version
        uses: jbutcher5/read-yaml@1.6
        with:
          file: "pubspec.yaml"
          key-path: '["version"]'

      - name: Build Android APK release
        id: build
        run: |
          mkdir keystore
          echo $ENCODED_KEYSTORE | base64 -d > keystore/upload-keystore.jks
          BUILD_NAME=${{ steps.version.outputs.data }}
          BUILD_NUMBER=$(git rev-list HEAD --count)
          flutter build apk --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER --release
          mv build/app/outputs/flutter-apk/app.apk build/app/outputs/flutter-apk/tentenone-$BUILD_NAME.apk
          echo "ANDROID_APK_NAME=$(echo tentenone-$BUILD_NAME.apk)" >> $GITHUB_OUTPUT
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_UPLOAD_SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_UPLOAD_SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_SIGNING_STORE_PASSWORD }}
          ENCODED_KEYSTORE: ${{ secrets.ANDROID_UPLOAD_KEYSTORE }}

      - name: Upload APK to job
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.build.outputs.ANDROID_APK_NAME}}
          path: build/app/outputs/flutter-apk/${{steps.build.outputs.ANDROID_APK_NAME}}

  release:
    needs: build
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from branch name
        id: extract-version
        shell: python
        run: |
          branch_name = "${{ github.event.pull_request.head.ref }}"
          version = branch_name.split("/")[1]

          print(f"::set-output name=version::{version}")

      - name: Extract changelog section for release
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.extract-version.outputs.version }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.ANDROID_APK_NAME }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ needs.build.outputs.ANDROID_APK_NAME }}
          body: ${{ steps.changelog.outputs.description }}
          token: ${{ secrets.ITCHY_GITHUB_TOKEN }}
          tag: ${{ steps.extract-version.outputs.version }}
