name: publish-docker

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      ref:
        required: false
        description: "The branch, tag or SHA to checkout. When omitted it will take latest main"
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup rust toolchain
        working-directory: "./"
        run: rustup show

      - uses: Swatinem/rust-cache@v2.0.1

      # unfortunately needed as it looks like we always compile the whole workspace
      - name: Install FFI bindings
        run: cargo install flutter_rust_bridge_codegen
      - name: Generate FFI bindings
        run: make gen

      - name: Login into github registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: cargo build --release --bin maker

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Build docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
          tags: ${{ steps.meta.outputs.tags }}
